djproject/djproject/urls.py
from django.contrib import admin
from django.urls import *

# gives available url options
urlpatterns = \
    [
        path(r'admin/', admin.site.urls),
        path(r'polls/', include('polls.urls', namespace="polls")),
    ]

djproject/polls/urls.py
from django.conf.urls import *
from . import views

urlpatterns = \
    [
        url(r'^$', views.index, name="index"),
        url(r'^(?P<question_id>[0-9]+)/$', views.detail, name="detail"),
        url(r'^(?P<question_id>[0-9]+)/results$', views.results, name="results"),
        url(r'^(?P<question_id>[0-9]+)/vote$', views.vote, name="vote"),
    ]
app_name = 'polls'

djproject/polls/models.py
from django.db import models


# Create your models here.

class Question(models.Model):
    objects = None
    question_text = models.CharField(max_length=100)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.choice_text

djproject/polls/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Question


# Create your views here.


def index(request):
    latest_questions = Question.objects.order_by('-pub_date')[0:5]
    context = {'latest_questions': latest_questions}
    return render(request, "polls/index.html", context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/detail.html", {"question": question})


def results(request, question_id):
    return HttpResponse("This is the results of the question %s" % question_id)


def vote(request, question_id):
    return HttpResponse("Votes on Question %s" % question_id)

djproject/polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
</head>
<body>

<hr>
<p> Header </p>
<hr>
    {% block main_content %}
    {% endblock %}
    {% include "polls/footer.html" %}
</body>
</html>

djproject/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block main_content %}
    <h1>{{question.question_text}}</h1>

    <form action="% url 'polls:vote' question.id %" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{forloop.counter}}" value ="{{choice.id}}"/>
            <label for ="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
        {% endfor %}
        <input type="submit" value ="vote"/>
    </form>


{% endblock %}

djproject/polls/templates/polls/footer.html
<hr>
<p>Footer</p>
<hr>

djproject/polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block main_content %}
    <ul>
    {% if latest_questions %}
        {% for question in latest_questions %}
        <li><a href={% url "polls:detail" question.id %}><b>{{question.question_text}}</b></a></li>
    {% endfor %}
    </ul>
    {% else %}
        <p>no questions, add some</p>
    {% endif %}

{% endblock %}